version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout
      - restore_cache:
          keys: 
            - gradle-{{ checksum "build.gradle" }}
      - run: gradle clean
      - run: gradle assemble
      - run: gradle test
      - save_cache:
          paths:
            - ~/.gradle
            key: gradle-{{ checksum "build.gradle" }}

      - store_artifacts:
          path: build/distributions
          destination: distributions
      - store_artifacts:
          path: build/libs
          destination: libs