version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo
    steps:
      - checkout
      - run: 
        - chmod +x gradlew
        - ./gradlew clean
        - ./gradlew assemble
        - ./gradlew test